name:                re-generate
version:             0.1.0.0
github:              "peterthiemann/re-generate"
license:             BSD3
author:              "Peter Thiemann"
maintainer:          "peter.thiemann@gmail.com"
copyright:           "2018 Peter Thiemann"

extra-source-files:
  - README.md
  - ChangeLog.md
description:         Please see the README on Github at <https://github.com/peterthiemann/re-generate#readme>

dependencies:
  - base >= 4.7 && < 5
  - timeit >= 2.0
  - containers >= 0.5
  - optparse-applicative >= 0.14
  - QuickCheck >= 2.9.2
  - deepseq
  - text
  - dlist
  - unordered-containers

library:
  source-dirs: src

executables:
  re-generate-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - re-generate

tests:
  re-generate-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - re-generate
      - hspec

benchmarks:
  re-bench:
    cpp-options: -DBENCH
    main: bench/Bench.hs
    ghc-options: -O2 -optc-O3 -threaded -rtsopts
    dependencies:
      - criterion
      - re-generate
